<?php include('includes/nav.php'); ?>

<section class="why-us">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1><i class="fa fa-gratipay"></i>Sub Ezy Partner</h1>
      </div>
      <?php include 'open-accts.php'; ?>
    </div>
  </div>
</section>

<!-- <section class="bonus-icons">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-gift pull-left"></i> Wide range of Bonuses
      </div>

      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-star-half pull-left"></i> 5% Interest Rate
      </div>

      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-google-wallet pull-left"></i> Variety of Account types
      </div>

      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-lock pull-left"></i> Funds Security
      </div>

      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-venus-double pull-left"></i> Fixed Spreads
      </div>

      <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2">
        <i class="fa fa-tasks pull-left"></i> Many Deposit Methods
      </div>
    </div>
  </div>
</section> -->

<?php include 'includes/bonus-icons.php' ?>

<section class="reg-start standard-partner">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <h4>Sub-Ezy Partner</h4>
        <p>EZYFX now gives you the opportunity to grow your own broker network with our Sub-Introducing Broker program. It works much in the same way as our <a href="partnership-programs.php">Introducing Broker</a> type of partnership, but instead of trying to recruit more traders, the goal of the sub-IB is to attract new partners. As a sub-IB, you will earn a bonus of 0.1 pips in commission from every trade made by the customers of the partners you have attracted. Expanding this partner network can increase your bonus to 0.2 pips.</p>
        <p>By becoming a EZYFX sub-IB you can take advantage of the following benefits:</p>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/1.png" alt="">
        <p class="lead">Earn on average $25 on the most popular trading currency pairs per standard lot on trades made by your referred clients</p>
        <p>We believe that you should be generously rewarded for your efforts which is why the EZYFX Partnership Program offers highly competitive commission rates. You can win on average $25 on the most popular trading currency pairs per standard lot on trades made by any clients you introduce to EZYFX.</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/2.png" alt="">
        <p class="lead">Earn unlimited 0.1 pips on new partners you attract</p>
        <p>Every time you introduce another partner to EZYFX, they automatically become a sub-partner of yours. As such, we reward you with 0.1 pips commission on all the earnings generated by that sub-partner. There is also no upper limit on sub-partner commissions. Contact the Partnership Department to learn more about commissions.</p>
      </div>
    </div>

    <div class="row">

      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/3.png" alt="">
        <p class="lead">No limit on commission per client</p>
        <p>Our Partnership Program offers an unlimited earning potential, meaning that there are no restrictions on how much profit you can make per client. For as long as your clients continue to trade, they will generate commissions for you. Since we do not impose a limit, the amount you earn depends entirely on the trading activity of your clients.</p>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/4.png" alt="">
        <p class="lead">Make Local Transfers easily</p>
        <p>In our effort to make the Partnership Program the most convenient for you, we grant you full flexibility by allowing the transfer of funds between both an IB account and a client trading account.</p>
        <p>Transfers can be made both ways with no charges or hidden fees incurred for the operations.</p>
      </div>
    </div>

    <div class="row">


      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/5.png" alt="">
        <p class="lead">Get paid on time</p>
        <p>The timely payment of your earnings is one of the most important aspects of the EZYFX Partnership Program. We ensure that your well-deserved commissions are paid to you on time, every time, with no hidden fees or charges.</p>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/6.png" alt="">
        <p class="lead">Personal Account Manager</p>
        <p>We can offer personalized guidance to our Partners in order to help you make the best decisions for your business development.</p>
      </div>
    </div>

    <div class="row">


      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/7.png" alt="">
        <p class="lead">Real-Time Reporting</p>
        <p>We provide you with access to live statistics and reports at any time from the easy-to-use Partner’s Cabinet. Review your account, conversion statistics, campaign charts and more; all in full detail.</p>
      </div>


      <div class="col-xs-12 col-sm-6 col-md-6">
        <img src="images/subezy/8.png" alt="">
        <p class="lead">Promotional Materials</p>
        <p>As a partner, you can employ a wide range of promo materials including banners, tracking links, merchandise, ready-made websites, APIs, certificates and seals developed by the EZYFX design team to aid you in attracting new clients.</p>
      </div>
    </div>
  </div>
</section>





<?php include('includes/footer.php'); ?>
